/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_testvideo_yuvconvert */
#include <android/log.h>

#ifndef _Included_com_example_testvideo_yuvconvert
#define _Included_com_example_testvideo_yuvconvert
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_testvideo_yuvconvert
 * Method:    convert
 * Signature: ([B[III)I
 */
JNIEXPORT jint JNICALL Java_com_example_testvideo_yuvconvert_convert
  (JNIEnv *, jclass, jbyteArray, jintArray, jint, jint);

JNIEXPORT jint JNICALL Java_com_example_testvideo_yuvconvert_convert1
  (JNIEnv *, jclass, jbyteArray, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
