/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_ffmpeglib_H264Decoder */

#ifndef _Included_com_android_ffmpeglib_H264Decoder
#define _Included_com_android_ffmpeglib_H264Decoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_ffmpeglib_H264Decoder
 * Method:    init
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_ffmpeglib_H264Decoder_init
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_android_ffmpeglib_H264Decoder
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_ffmpeglib_H264Decoder_release
  (JNIEnv *, jobject);

/*
 * Class:     com_android_ffmpeglib_H264Decoder
 * Method:    decode
 * Signature: ([B[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_ffmpeglib_H264Decoder_decode
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
